# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-avatar

# Permalinks
permalink: pretty

# Setup
url: 'https://earlynovels.github.io'

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl: ''

title: Peter Yang's Webware

# Pagination
paginate: 5
paginate_path: '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description: >
  random dump for personal page

# The tags listed as entries in the sidebar
sidebar_tags: [blog]

# Ignore vendor directory
exclude: [vendor]

# Fallback image and color if not overwritten for tag or post
image: /public/img/galaxy.jpeg
color: '#A85641'

# Fonts
font: '"PT Serif", Georgia, serif'
font_accent: '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts: 'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  # name:              'Peter Yang'
  #
  #   # This photo will be used in the about section
  picture: /public/img/ME.png
  #   photo:             http://qwtel.com/public/img/flo.jpg
  #   photo2x:           http://qwtel.com/public/img/flo@2x.jpg
  #
  #   # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  #   about:             |
  #     [fill in some text about END]

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    github: AprilSweettooth
    twitter: Peter00351335
    facebook: AprilSweettooth
    # google: _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    instagram: peter.ysqh
    # flickr: 97741188@N04
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    linkedin: peter-yang-0a1b791b9
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
# google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
disqus: https-aprilsweettooth-github-io-homepage

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

compress_html:
  comments: ['<!-- ', ' -->']
  clippings: all
  endings: all
  ignore:
    envs: [local]

sass:
  style: compressed

collections:
  years:
    output: true
    permalink: /people/:path
  profiles:
    output: true
    permalink: /people/:path
  projects:
    output: true
    permalink: /projects/:path
